name: Deploy

on:
  push:
    branches:
      - deploy/api/dev
      - deploy/api/alpha
    paths:
      - "packages/api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Deploy to environment
        working-directory: packages/api
        run: |
          yarn
          if [[ $GITHUB_REF == "refs/heads/deploy/api/dev" ]]; then
            yarn run deploy:dev
          elif [[ $GITHUB_REF == "refs/heads/deploy/api/alpha" ]]; then
            yarn run deploy:alpha
          fi
